BLD/accounts/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.view_logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
]

BLD/base_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "base_app"

urlpatterns = [
    path('', views.base, name="base"),
    path('restaurant/<int:pk>', views.restaurant, name="restaurant"),
    path('all_comments', views.all_comments, name="all_comments"),
    path('restaurant/<int:pk>/write_comment', views.write_comment, name="write_comment"),
    path('like', views.comment_like, name='comment_like'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BLD/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base_app/', include('base_app.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BLD/base_app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from imagekit.processors import Thumbnail
from imagekit.models import ProcessedImageField


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=20, verbose_name='카테고리명',)
    category_image = models.ImageField(blank=True, verbose_name='카테고리 사진',)

    def __str__(self):
        return self.category_name


class Menu(models.Model):
    category = models.CharField(max_length=20, verbose_name='음식 종류(밥, 국, 주류...)',)
    name = models.CharField(max_length=20, verbose_name='음식명',)
    price = models.IntegerField(verbose_name='음식 가격',)

    # 아마 이 평점이 나중에 각 음식별 평점으로 쓰일 듯
    # dish_star = models.IntegerField(verbose_name='음식 평점',)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    name = models.CharField(max_length=12, verbose_name='음식점 이름',)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE, verbose_name='카테고리',)
    # main_image = models.ImageField(blank=True, verbose_name='음식점 사진',)
    phone_number = models.CharField(blank=True, max_length=17, verbose_name='음식점 전화번호',)
    menu = models.ForeignKey(Menu, null=True, blank=True, on_delete=models.CASCADE, verbose_name='음식점 메뉴',)
    open_to_close = models.TextField(blank=True, verbose_name='오픈 & 마감',)
    STATUS_CHOICES = (
        ('O', 'O'),
        ('X', 'X'),
        ('-', '-'),
    )
    is_package_possible = models.TextField(blank=True, choices=STATUS_CHOICES, verbose_name='포장 가능 여부', )
    is_delivery_possible = models.TextField(blank=True, choices=STATUS_CHOICES, verbose_name='배달 가능 여부', )
    is_card_possible = models.TextField(blank=True, choices=STATUS_CHOICES, verbose_name='카드 가능 여부', )
    detail = models.TextField(blank=True, verbose_name='음식점 설명',)
    latitude = models.CharField(max_length=20,)
    longitude = models.CharField(max_length=20,)
    register = models.DateTimeField(auto_now_add=True, verbose_name='음식점 등록일',)

    # 경도, 위도로 장소 자동추가
    def locate(self):
        locate = "{lat:" + self.latitude + ", lng:" + self.longitude + "}"
        return locate

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자', null=True,)   # Profile의 user와 같은 거?? 따로 부름??
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, verbose_name='해당 가게')

    # TODO: 구글 평점 가져오기
    STATUS_CHOICES = (
        (4, 'A'),
        (3, 'B'),
        (2, 'C'),
        (1, 'D'),
        (0, 'F'),
    )
    price_star = models.IntegerField(verbose_name='가격 만족도',)
    taste_star = models.IntegerField(verbose_name='맛 만족도',)
    clean_star = models.IntegerField(verbose_name='청결성 만족도',)
    dish_eaten = models.CharField(max_length=30, blank=True, null=True, verbose_name='먹은 음식',)
    content = models.CharField(max_length=160, verbose_name='150자평', blank=True, null=True,)
    food_image = ProcessedImageField(
        upload_to="blog/%Y/%m/%d", blank=True, null=True,
        # processors=[Thumbnail(500, 500)],  # 처리할 작업 목룍
        format='JPEG',  # 최종 저장 포맷
        options={'quality': 70}  # 저장 옵션
    )
    STATUS_CHOICES = (
        ('꼭 다시 먹는다', '꼭 다시 먹는다'),
        ('잘 모르겠다', '잘 모르겠다'),
        ('절대 안 먹는다', '절대 안 먹는다'),
    )
    try_again = models.TextField(choices=STATUS_CHOICES, verbose_name='다시 먹을 지 여부', null=True, blank=True,)

    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')
    @property
    def like_count(self):
        return self.like_user_set.count()

    # police = models.IntegerField(verbose_name='신고 수',)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def average_star(self):
        average_star = self.taste_star / 2 + self.price_star / 4 + self.clean_star / 4
        return average_star

    # comment 쓰고 다시 그 페이지로(그대로 따옴, 수정 필요)
    # def get_absolute_url(self):
    #     return reverse('main_app:product', args=[self.product.id])


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='유저')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='해당 후기')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

BLD/base_app/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['restaurant', 'taste_star', 'price_star', 'clean_star', 'dish_eaten', 'content', 'food_image', ]

BLD/base_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Restaurant, Category, Comment
from .forms import CommentForm
from django.db.models import Q, Avg
from django.contrib.auth.decorators import login_required
import os, json
from django.core.exceptions import ImproperlyConfigured
from django.views.decorators.http import require_POST
from django.http import HttpResponse


# Create your views here.
def base(request):
    # 숫자로 받은 값을 grade 시스템으로
    def number_to_grade(self):
        if self > 4:
            grade = 'A+'
        elif self >= 3.5:
            grade = 'A'
        elif self > 3:
            grade = 'B+'
        elif self >= 2.5:
            grade = 'B'
        elif self > 2:
            grade = 'C+'
        elif self >= 1.5:
            grade = 'C'
        elif self > 1:
            grade = 'D+'
        elif self >= 0.5:
            grade = 'D'
        else:
            grade = 'F'
        return grade

    def sum_none(a, b, c):
        if a is None:
            a = 0
            b = 0
            c = 0
        return a / 2 + b / 4 + c / 4

    def comment_star(x, y):
        return x.comment_set.all().aggregate(Avg(y))[y + '__avg']

    # GOOGLE MAP SECRET_KEY
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    secret_file = os.path.join(BASE_DIR, './secrets.json')  # secrets.json 파일 위치를 명시
    with open(secret_file) as f:
        secrets = json.loads(f.read())

    def get_secret(setting, secrets=secrets):
        """비밀 변수를 가져오거나 명시적 예외를 반환한다."""
        try:
            return secrets[setting]
        except KeyError:
            error_msg = "Set the {} environment variable".format(setting)
            raise ImproperlyConfigured(error_msg)

    GOOGLE_MAP_KEY = "https://maps.googleapis.com/maps/api/js?key=" + get_secret("GOOGLE_MAP_KEY") + "&callback=initMap"

    # filter 구현
    if "category" in request.GET:
        sort_term = request.GET["sort"]
        category = request.GET["category"]
        category = category.split(',')
        category_term = []
        for a in category:
            b = a.splitlines()[0]
            category_term.append(b)

        restaurants = Restaurant.objects.filter(category__category_name__in=category_term)
        categorys = Category.objects.all()
        # comment 에 있는 average_star 다 더해서 전체 평점 구하기
        for restaurant in restaurants:
            restaurant.comment_count = "(" + str(restaurant.comment_set.all().count()) + ")"
            if restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg'] is None:
                restaurant.average_star = "-"
            else:
                taste_star = restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg']
                price_star = restaurant.comment_set.all().aggregate(Avg('price_star'))['price_star__avg']
                clean_star = restaurant.comment_set.all().aggregate(Avg('clean_star'))['clean_star__avg']
                restaurant.taste_star = number_to_grade(taste_star)
                restaurant.price_star = number_to_grade(price_star)
                restaurant.clean_star = number_to_grade(clean_star)
                restaurant.average_star = number_to_grade(taste_star / 2 + price_star / 4 + clean_star / 4 + 0.2)
            restaurant.save()

        # sort로 분류
        if sort_term == "평점순":
            restaurants = sorted(restaurants,
                                 key=lambda x: sum_none(comment_star(x, 'taste_star'), comment_star(x, 'price_star'),
                                                        comment_star(x, 'clean_star'))
                                 , reverse=True)
        elif sort_term == "인기순":
            restaurants = sorted(restaurants, key=lambda x: x.comment_set.count(), reverse=True)
        else:
            restaurants = restaurants

        # restaurant numbering
        i = 1
        for restaurant in restaurants:
            restaurant.number = i
            i += 1
            restaurant.save()

        ctx = {
            'GOOGLE_MAP_KEY': GOOGLE_MAP_KEY,
            'sort_term': sort_term,
            'categorys': categorys,
            'restaurants': restaurants,
        }
        return render(request, 'base_app/base.html', ctx)

    # search 구현
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            searched_restaurants = Restaurant.objects.filter(
                Q(name__icontains=search_term) |
                Q(menu__category__icontains=search_term) |
                Q(menu__name__icontains=search_term) |
                Q(category__category_name__icontains=search_term) |
                Q(detail__icontains=search_term)
            ).distinct()

        # comment 에 있는 average_star 다 더해서 전체 평점 구하기
        for restaurant in searched_restaurants:
            restaurant.comment_count = "(" + str(restaurant.comment_set.all().count()) + ")"
            if restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg'] is None:
                restaurant.average_star = "-"
            else:
                taste_star = restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg']
                price_star = restaurant.comment_set.all().aggregate(Avg('price_star'))['price_star__avg']
                clean_star = restaurant.comment_set.all().aggregate(Avg('clean_star'))['clean_star__avg']
                restaurant.taste_star = number_to_grade(taste_star)
                restaurant.price_star = number_to_grade(price_star)
                restaurant.clean_star = number_to_grade(clean_star)
                restaurant.average_star = number_to_grade(taste_star / 2 + price_star / 4 + clean_star / 4 + 0.2)
            restaurant.save()

        # 필터별 restaurants 분류
        sort_grade = sorted(searched_restaurants,
                            key=lambda x: sum_none(comment_star(x, 'taste_star'), comment_star(x, 'price_star'),
                                                   comment_star(x, 'clean_star'))
                            , reverse=True)
        categorys = Category.objects.all()

        # restaurant numbering
        i = 1
        for restaurant in sort_grade:
            restaurant.number = i
            i += 1
            restaurant.save()

        ctx = {
            'GOOGLE_MAP_KEY': GOOGLE_MAP_KEY,
            'search_term': search_term,
            'restaurants': sort_grade,
            'categorys': categorys,
        }
        return render(request, 'base_app/base.html', ctx)

    restaurants = Restaurant.objects.all()
    categorys = Category.objects.all()

    # comment 에 있는 average_star 다 더해서 전체 평점 구하기
    for restaurant in restaurants:
        restaurant.comment_count = "(" + str(restaurant.comment_set.all().count()) + ")"
        if restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg'] is None:
            restaurant.average_star = "-"
        else:
            taste_star = restaurant.comment_set.all().aggregate(Avg('taste_star'))['taste_star__avg']
            price_star = restaurant.comment_set.all().aggregate(Avg('price_star'))['price_star__avg']
            clean_star = restaurant.comment_set.all().aggregate(Avg('clean_star'))['clean_star__avg']
            restaurant.taste_star = number_to_grade(taste_star)
            restaurant.price_star = number_to_grade(price_star)
            restaurant.clean_star = number_to_grade(clean_star)
            restaurant.average_star = number_to_grade(taste_star / 2 + price_star / 4 + clean_star / 4 + 0.2)
        restaurant.save()

    # 필터별 restaurants 분류
    sort_grade = sorted(restaurants,
                        key=lambda x: sum_none(comment_star(x, 'taste_star'), comment_star(x, 'price_star'),
                                               comment_star(x, 'clean_star'))
                        , reverse=True)

    # restaurant numbering
    i = 1
    for restaurant in sort_grade:
        restaurant.number = i
        i += 1
        restaurant.save()

    ctx = {
        'GOOGLE_MAP_KEY': GOOGLE_MAP_KEY,
        'categorys': categorys,
        'restaurants': sort_grade,
    }
    return render(request, 'base_app/base.html', ctx)


def restaurant(request, pk):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    secret_file = os.path.join(BASE_DIR, './secrets.json')  # secrets.json 파일 위치를 명시
    with open(secret_file) as f:
        secrets = json.loads(f.read())

    def get_secret(setting, secrets=secrets):
        """비밀 변수를 가져오거나 명시적 예외를 반환한다."""
        try:
            return secrets[setting]
        except KeyError:
            error_msg = "Set the {} environment variable".format(setting)
            raise ImproperlyConfigured(error_msg)

    GOOGLE_MAP_KEY = "https://maps.googleapis.com/maps/api/js?key=" + get_secret("GOOGLE_MAP_KEY") + "&callback=initMap"

    restaurants = Restaurant.objects.all()
    categorys = Category.objects.all()
    selected_restaurant = Restaurant.objects.filter(pk=pk)
    comments = Comment.objects.filter(restaurant__pk=pk)

    # 숫자로 받은 값을 grade 시스템으로
    def number_to_grade(self):
        if self > 4:
            grade = 'A+'
        elif self >= 3.5:
            grade = 'A'
        elif self > 3:
            grade = 'B+'
        elif self >= 2.5:
            grade = 'B'
        elif self > 2:
            grade = 'C+'
        elif self >= 1.5:
            grade = 'C'
        elif self > 1:
            grade = 'D+'
        elif self >= 0.5:
            grade = 'D'
        else:
            grade = 'F'
        return grade

    for comment in comments:
        comment.taste_grade = number_to_grade(comment.taste_star)
        comment.price_grade = number_to_grade(comment.price_star)
        comment.clean_grade = number_to_grade(comment.clean_star)
        comment.average_grade = number_to_grade(comment.average_star())
        comment.save()

    # comment 에 있는 average_star 다 더해서 전체 평점 구하기
    for restaurant in restaurants:

BLD/base_app/templates/base_app/all_comments.html
{% extends "base_app/base.html" %}

{% block head_left %}
{% load static %}
  {% if search_term %}
    <div class="main_menu">‘{{ search_term }}’ <span>의 검색 결과</span></div>
  {% else %}
    <div class="main_menu">후기</div>
  {% endif %}
{% endblock %}

{% block head_right23 %}
{% endblock %}

{% block search %}
<input class="search_text" type="text" name="search" placeholder="(후기) 검색어를 입력해주세요" required>
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'base_app/css/restaurant.css' %}">
<div class="comment_list">
  {% for comment in comments %}
    <div class="comment">
      <!--writer-->
      <div class="profile_set">
      {% if comment.author.is_superuser or comment.author.is_staff %}
        <div class="profile_image"><img src="{% static 'base_app/images/profile1.png' %}" width="35"></div>
        <div class="profile_content">
          <div class="profile_nickname" style="color: rgb(255,129,129)">{{ comment.author.last_name }}</div>
      {% else %}
        <div class="profile_image"><img src="{% static 'base_app/images/profile2.png' %}" width="35"></div>
        <div class="profile_content">
          <div class="profile_nickname" style="color: rgb(129,129,255)">{{ comment.author.last_name }}</div>
      {% endif %}
          <div class="upload_time">
            <span>{{ comment.created_at|date:"y/m/d" }}</span>
            <span>{{ comment.created_at|time:"H:i" }}</span>
          </div>
        </div>
        <div class="comment_restaurant">
          <a href="{% url "base_app:restaurant" pk=comment.restaurant.pk %}"># <span>{{ comment.restaurant }}</span></a>
          {% if comment.dish_eaten %}
          <a href="#"><{{ comment.dish_eaten }}></a>
          {% endif %}
        </div>
      </div>

      <!--comment-->
      <div class="comment_set">
        <div class="comment_content">{{ comment.content }}</div>
          <div class="grade_set">
            <span class="taste"><b>맛</b><span> {{ comment.taste_grade }}</span></span>
            <span class="cost"><b>가격</b><span> {{ comment.price_grade }}</span></span>
            <span class="clean"><b>청결</b><span> {{ comment.clean_grade }}</span></span>
            <span class="like" name="{{ comment.id }}"><span><img src="{% static 'base_app/images/like.png' %}" width="12"></span><span id="count-{{ comment.id }}"> {{ comment.like_count }}</span></span>
          </div>
        <div class="comment_images">
          {% if comment.food_image %}
          <img class="comment_image" src="{{ comment.food_image.url }}">
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

{% block footer %}
<a href="{% url "base_app:all_comments" %}"><img src="{% static 'base_app/images/comment2.png' %}" width="26"></a>
<a href="{% url "base_app:base" %}"><img src="{% static 'base_app/images/restaurant1.png' %}" width="27"></a>
<a href="{% url "base_app:write_comment" pk=1 %}"><img src="{% static 'base_app/images/write1.png' %}" width="27"></a>
<a href="#"><img src="{% static 'base_app/images/gear1.png' %}" width="27"></a>
{% endblock %}


{% block mapMarker %}
{% endblock %}

BLD/base_app/templates/base_app/restaurant.html
{% extends "base_app/base.html" %}

{% block main_title %}
{% load static %}
  {% for restaurant in selected_restaurant %}
    <div class="main_title">{{ restaurant.name }}</div>
  {% endfor %}
{% endblock %}


{% block head_right23 %}
<div class="map" id="head_right1">
  <img src="{% static 'base_app/images/map.png' %}" height="25">
</div>
{% endblock %}

{% block head_right1 %}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base_app/css/restaurant.css' %}">
<div class="comment_list">
  {% for restaurant in selected_restaurant %}
    <div class="restaurant_set {{ restaurant.category }}">
      <div class="restaurant_image"></div>
      <div class="restaurant_content">
        <div class="restaurant_content_left">
          <div class="restaurant_name">{{ restaurant }}</div>
          <div class="restaurant_info">010-0000-0000<br>0요일 오후 0시 ~ 오후 0시</div>
          <div class="restaurant_star">
            <b>{{ restaurant.average_star }}</b><span class="comment_count"> {{ restaurant.comment_count }}</span>
            <span>맛 {{ restaurant.taste_star }}  가격 {{ restaurant.price_star }}  청결 {{ restaurant.clean_star }}</span>
          </div>
        </div>
        <div class="restaurant_content_right">
          <div><span>혼밥 </span><span>{% if restaurant.is_card_possible %}{{ restaurant.is_card_possible }}{% else %}-{% endif %}</span></div>
          <div><span>포장 </span><span>{% if restaurant.is_package_possible %}{{ restaurant.is_package_possible }}{% else %}-{% endif %}</span></div>
          <div><span>배달 </span><span>{% if restaurant.is_delivery_possible %}{{ restaurant.is_delivery_possible }}{% else %}-{% endif %}</span></div>
        </div>
      </div>
      <div class="comments">메<br>뉴<br>보<br>기</div>
    </div>
  {% endfor %}
  {% for comment in comments %}
    <div class="comment">
      <!--writer-->
      <div class="profile_set">
      {% if comment.author.is_superuser or comment.author.is_staff %}
        <div class="profile_image"><img src="{% static 'base_app/images/profile1.png' %}" width="35"></div>
        <div class="profile_content">
          <div class="profile_nickname" style="color: rgb(255,129,129)">{{ comment.author.last_name }}</div>
          <div class="upload_time">
            <span>{{ comment.created_at|date:"y/m/d" }}</span>
            <span>{{ comment.created_at|time:"H:i" }}</span>
          </div>
        </div>
        <div class="comment_restaurant">
          <a href="{% url "base_app:restaurant" pk=comment.restaurant.pk %}"># <span>{{ comment.restaurant }}</span></a>
          {% if comment.dish_eaten %}
          <a  href="#"><{{ comment.dish_eaten }}></a>
          {% endif %}
        </div>
      {% else %}
        <div class="profile_image"><img src="{% static 'base_app/images/profile2.png' %}" width="35"></div>
        <div class="profile_content">
          <div class="profile_nickname" style="color: rgb(129,129,255)">{{ comment.author.last_name }}</div>
          <div class="upload_time">
            <span>{{ comment.created_at|date:"y/m/d" }}</span>
            <span>{{ comment.created_at|time:"H:i" }}</span>
          </div>
        </div>
        <div class="comment_restaurant">
          <a href="{% url "base_app:restaurant" pk=comment.restaurant.pk %}"># <span>{{ comment.restaurant }}</span></a>
          {% if comment.dish_eaten %}
          <a  href="#"><{{ comment.dish_eaten }}></a>
          {% endif %}
        </div>
      {% endif %}
      </div>

      <!--comment-->
      <div class="comment_set">
        <div class="comment_content">{{ comment.content }}</div>
        <div class="grade_set">
          <span class="taste"><b>맛</b><span> {{ comment.taste_grade }}</span></span>
          <span class="cost"><b>가격</b><span> {{ comment.price_grade }}</span></span>
          <span class="clean"><b>청결</b><span> {{ comment.clean_grade }}</span></span>
          <span class="like" name="{{ comment.id }}"><span><img src="{% static 'base_app/images/like.png' %}" width="12"></span><span id="count-{{ comment.id }}"> {{ comment.like_count }}</span></span>
        </div>
        <div class="comment_images">
          {% if comment.food_image %}
          <img class="comment_image" src="{{ comment.food_image.url }}">
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

{% block footer %}
<a href="{% url "base_app:all_comments" %}"><img src="{% static 'base_app/images/comment1.png' %}" width="26"></a>
<a href="{% url "base_app:base" %}"><img src="{% static 'base_app/images/restaurant2.png' %}" width="27"></a>
{% if user.is_authenticated %}
  {% for restaurant in selected_restaurant %}
  <a href="{% url "base_app:write_comment" pk=restaurant.pk %}"><img src="{% static 'base_app/images/write1.png' %}" width="27"></a>
  {% endfor %}
{% else %}
  <a href="{% url "accounts:login" %}"><img src="{% static 'base_app/images/write1.png' %}" width="27"></a>
{% endif %}
<a href="#"><img src="{% static 'base_app/images/gear1.png' %}" width="27"></a>
{% endblock %}

{% block start_html %}
{% endblock %}
{% block start_js %}
{% endblock %}

<!--map 설정-->
{% block mapZoom %}
  {% for restaurant in selected_restaurant %}
    center: {{ restaurant.locate }},
  {% endfor %}
  zoom: 19,
{% endblock %}

{% block newMarker %}
      // 해당 restaurant 소개 바로 뜨게
  {% for restaurant in selected_restaurant %}
      var selectedMarker = new google.maps.Marker({
          position: {{ restaurant.locate }},
          map: map,
          zIndex: 19980206,
          label: {
              text: "★",
              fontSize: '12px',
              fontWeight: '900',
              color: 'rgb(255,129,129)',
          },
          icon: image1,
      });

      // 클릭 시 restaurant 소개 & 센터 오게
      var restaurant_introduction =
          '    <div style="display: flex; align-items: center; justify-content: space-between; width: 160px; height: 40px; margin-top: 5px; text-align: left; font-weight: 900">\n' +
          '      <div>{{ restaurant }}<span style="color: rgb(255,192,0)">({{ restaurant.average_star }})</span></div>\n' +
          '      <a href="{% url "base_app:restaurant" pk=restaurant.pk %}" style="all: unset; text-decoration: underline black">후기 / 정보</a>\n' +
          '    </div>';
      var infowindow = new google.maps.InfoWindow({
          content: restaurant_introduction
      });

      selectedMarker.addListener('click', function() {
          map.setZoom(21);
          map.panTo(this.getPosition());
          infowindow.open(map, selectedMarker);
      });
  {% endfor %}
{% endblock %}